### ISSUE TITLE
Add support for relative dates in the `--date` argument

### ISSUE THREAD

**Issue by Deuchnord** [Deuchnord/kosmorro#74]
**Is your feature request related to a problem? Please describe.**
Since version 0.7, the `--day`, `--month` and `--year` arguments have been removed in the favor of a single, more simple `--date` one.
But as a side-effect, calculating the ephemerides of the next days is now much more painful, because we now need to give the entire date: before, we could give the --day only for instance, and the month and year were automatically guessed to the current ones.

**Describe the solution you'd like**
Add the capacity for the `--date` argument to understand relative dates. The solution I imagine is something inspired from [PHP's `DateInterval` constructor](https://www.php.net/manual/en/dateinterval.construct.php), but in a more user-friendly style.

The format would follow the following regular expression:
```regexp
^([+-])(([0-9]+)y)?[ ]?(([0-9]+)m)?[ ]?(([0-9]+)d)?$
```
- The string starts with a `+` or a `-` character.
- Each duration period is represented by an integer value followed by one of the following period designators:
   - `d` for days,
   - `m` for months,
   - `y` for years.
- Each part of the duration value is optional, but there must be at least one of them for the string to be a valid period.
- There may be spaces between each part of the interval.

Examples of valid intervals:
- `+1d` (tomorrow)
- `+1m2d` (in one months and two days)
- `+1y2m` (in one year and two months)
- `+1y 2m` (same)

**Describe alternatives you've considered**
Currently, the only possible alternative is to give the entire date in the `YYYY-MM-DD` format.

**Comment by Brainface1** [comment]
I have implemented the basics of this (https://github.com/Brainface1/kosmorro) however i have two questions:
1. I added a new dependency (dateutil for its relativedelta implementation) is this ok?
2. argparse doesnt allow leading dashes as arguments, because it recognizes them as flags. Does someone have a suggestion for working around this issue?

**Comment by Deuchnord** [comment]
Hello, thanks for your work! Feel free to open a PR when you want :)

> I added a new dependency (dateutil for its relativedelta implementation) is this ok?

I didn't know this library, if you think it it should be used, feel free to add it :)
Don't forget to use `pipenv install <library name>` to update the Pipfile to ensure the lock file is up-to-date.

> argparse doesnt allow leading dashes as arguments, because it recognizes them as flags. Does someone have a suggestion for working around this issue?

Can reproduce this too… According to [this answer](https://stackoverflow.com/a/52636344/3328268) on StackOverflow, you can use either the `--date=<offset>` or the `-d=<offset>` format instead :)
